language: java
jdk:
  - oraclejdk8
env:
  global:
  - secure: A4e9OPh4eS4hnF5qTOH18YK/tbGuKlPQGdskK8Lot6eSHLX4yDdtpuRRqJ+6ULrjc9NYjtcDy0BtKs9D5+OvkNvolY+JEGQM9kMF7BOJ9GcO2ogFAabGMii7oX/hNXtV9/JsnZt9GrEuN0JcLlGFTZjV57jQzJVEeK4Hs1hojwHXmvpf7264HTpgr1OaQFzejnIYX/95N5jRGthrDH8Kwnz9Ab5heFmamcZe9cgrMCTp5+FbpJOXVLfLhY9YTh76ZwDoVWRYJInqLimB6FlxjYvmPkM9Ea0acwzl30kG+QKpiyAcei+EkA0sDqrQNvIJ/nW9HvK/oYcdIhJZVP9iYA61hYXf4Oh57tK35TR/grg4U4MTLd83cQBfVdGzdT9pE0/neEx4HC05tgjiLigs14HCqe8ImOVIvKNLOkXDhg1l3iZQdMbyvid7gIGJNBvmoORgvEG1x3J4aohruEGj+sLYhfi9UADwofg6/SXk2k7P34+CzL9E4L1agA7bgrXn6UuaY3WDzKbJ6kOae0jFdbT6iwNZnXfjdmJFISN/VnsW3rrOdQ1bA9qMP68LTqtyX/L2wYbcXI2jcWH0GTp8RE6zLq8DVpyqHJCLK0QJgY7pv92S04U0NMfM8ynupURrtJDCT7klyV7dMVsBSW37VZvy/YZseCtFd5oBk69PBJ8=
  - secure: vpSFv+wKHUsQJMUMeIdFYNqyFlLhWppza+PcdNs/DxkSW0y3vYcFeR0s9QUqmx6g4yrmNQpR3B6Jf70Wr9eHj3Pd1ak2f+8Knzgz5QFIQd4WmK181wv4oDRDTx09eYkghFq/Zh9sHdR5SGp8aPpX7Ae2nW0C3c3JVWd7V2z8ga2kB40rRwwBbATOjcq4S8PGhcp0wuoACTzkrg2c061UMhyxVLyPUU+/zQ3oE+8GE9T7ZG60ICG4ugopcPtEZdfI/qSU8RfC8jH67Vdnl05schjpnZHVC3u3Vq2TiTvWw625yBdjQWX3G/vgPDQzXMiZ9l11dYwbpWBm0HWC0SXIy1zrvcw4UrGKpfNpdn1YKjVH6YFL2Zpd2d84ygXWlYPcCzyaI85YuBQ0X6Uj686JseTNJWpwux4koL7ZW0rY0uaXZg9rIaZhxwWTliMjOo1dAQLh5YQbGud4hIvBnPXXCdRPifSkLpy7zUpJgCpyQdKA5HIfuZO9bdLpgWV9vi/Po8PLQnm6OTHzJKzdK9aZO39R9RTNS90WD23KMHI4+DqEdfnWy7Unq5bPCkzu0FetGguCzG2pBVID/8lHoeVebRLbL8YlwS9dXZQKtNJN2iJmWH4o3XLXzrAow9aopIYn3pTEwfrg09RrTcDvVdPjakwLugJ3HzbDDRZeAUOh9E0=
  - secure: AOxadSu0VJlt+vP9+U7IHQVAjNSGeO4e1EzF6uoHkUQxCd7GI7E1PNFMxA6MDAxVG+ns2a3GndaHDRV51RRqHHvZ8MNb8x7PuzunneJT+bE1FyppIcGXECNWeDuOvu4ByCSFXxzKAb5AQuVzt49G+LduF0928YSlQ0mpiumEB8l5l0deNe4jqO0fc3ULMCNluOBIzH0YQ4p+5Nsr/RAb/5nfALpEm8OmtVa/kAouKMwXq6Kory3yRBKPt1pkM/XOT6c8G9oSubGzgJQab/LE5bGVOPcvBUmx9SIOTNIv3MaZOVLFHV6pkr/nEzBcKDcZvJEr+1Ng5yx7K+jncWcdm11otXQzv7kINUfhbbv2Fz3MFXyYTvBfHXVGhVoVrBibpSczrC1drTqtGs+YsNRnIE90X9o6tjU8EtceL+FW8UTRgnB1SahlhhyBy9+gM+ldUOUXY/0UGDw0Dh+3uFoQalrmAuEP7ZZkVbKnEav1IwWtOM/snOc1bB/OSE6eQ5ca5s6T0Bcee+RVl5PPmP+KSJ5PmMxbJa3xogLIno4T8KBfVo9NiAMW9rbVUX5kV6kUZUVcfpghTtl25l4cg/qQwvfDeHw0SZodz3u3YcjkHeVROxgKvmgg6ixi3X6lr6icWC5t1XPsDNHUlxr8BzLtMxWldhkR0y3h4inkh97xQGU=
install:
  -
branches:
  except:
    - /^releases.*$/
script:
  - chmod ugo+x bin/*.sh
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bin/build.sh || false'
  # don't deploy on pull request
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && mvn verify --settings settings.xml || true'
cache:
  directories:
    - '$HOME/.m2/repository'
